# https://www.home-assistant.io/components/media_player.panasonic_viera/
# https://www.home-assistant.io/components/media_player.samsungtv/
# https://github.com/JeffLIrion/homeassistant_native_firetv
# https://www.home-assistant.io/components/media_player.firetv/
# https://www.home-assistant.io/components/cast/

alexa_media:
  accounts:
    - email: !secret amz_email
      password: !secret amz_password_key
      url: 'amazon.com'

media_player:
  # - platform: alexa
  #   email: !secret amz_email
  #   password: !secret amz_password_key
  #   url: 'amazon.com'
# - platform: firetv
  #   adbkey: "/config/packages/firetv/adbkey"
  #   host: !secret firetvbox_ip
  #   name: Fire TV
  # - platform: firetv
  #   adbkey: "/config/packages/firetv/adbkey"
  #   host: !secret firetvstick_ip
  #   name: Fire TV Stick
  - platform: panasonic_viera
    name: Livingroom TV
    host: !secret livingroom_tv_ip
  - platform: samsungtv
    name: Office TV
    host: !secret office_tv_ip

cast:
  media_player:
    - host: !secret ghomem1_ip
    # - host: !secret googlecast1_ip
    - host: !secret shield_ip

remote:
  - platform: harmony
    name: Livingroom
    host: !secret harmonyhub_ip
    activity: Watch TV

shell_command:
  update_alexa_command: '/usr/bin/curl -L -o /config/custom_components/media_player/alexa.py https://github.com/keatontaylor/custom_components/raw/master/media_player/alexa.py'

script:
  update_alexa :
    alias: Update alexa component
    sequence:
      - service: shell_command.update_alexa_command
