# https://www.home-assistant.io/components/sensor.command_line/
# https://github.com/andrey-git/home-assistant-custom-ui

homeassistant:
  customize:
    sensor.printer_name:
      friendly_name: Model
      icon: mdi:printer
    sensor.printer_serial:
      friendly_name: Serial Number
    sensor.printer_firmware:
      friendly_name: Firmware
      icon: mdi:code-tags
    sensor.printer_status:
      friendly_name: Status
      icon: mdi:information-outline
    sensor.printer_drum_pct_remain:
      friendly_name: Drum Remaining
      icon: mdi:panorama-vertical
      hidden: true
    sensor.printer_drum_page_remain:
      friendly_name: Drum Pages Remaining
      icon: mdi:file-document
    sensor.printer_toner_pct_remain:
      friendly_name: Toner Remaining
      icon: mdi:blur
      hidden: true
    sensor.printer_toner_page_remain:
      friendly_name: Toner Pages Remaining
      icon: mdi:file-document
    script.cleaning_mode:
      icon: mdi:printer

sensor:
  - platform: command_line
    name: printer_name
    command: !secret printer_product_name_url
    scan_interval: 86400
  - platform: command_line
    name: printer_serial
    command: !secret printer_serial_number_url
    scan_interval: 86400
  - platform: command_line
    name: printer_firmware
    command: !secret printer_firmware_url
    scan_interval: 86400
  - platform: command_line
    name: printer_status
    command: !secret printer_status_url
    scan_interval: 3600
  - platform: command_line
    name: printer_toner_pct_remain
    unit_of_measurement: '%'
    command: !secret printer_toner_percent_url
    scan_interval: 86400
  - platform: command_line
    name: printer_toner_page_remain
    command: !secret printer_toner_pages_url
    scan_interval: 86400
  - platform: command_line
    name: printer_drum_pct_remain
    unit_of_measurement: '%'
    command: !secret printer_drum_percent_url
    scan_interval: 86400
  - platform: command_line
    name: printer_drum_page_remain
    command: !secret printer_drum_pages_url
    scan_interval: 86400

shell_command:
  clean_printer: !secret printer_cleaning_mode_url

script:
  cleaning_mode:
    alias: Cleaning mode
    sequence:
      - service: shell_command.clean_printer
