show_installable: false
hide_sensor: false
track:
  - cards
  - components

card_urls:
  - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json
  - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json

component_urls:
  - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  - https://raw.githubusercontent.com/forwardcomputers/home-assistant/master/config/custom_components/custom_components.json
